SELECT * FROM C##KH.JOB;

-- 관리자계정으로 KH테이블에 접근할 수 있는 권한 부여
GRANT ALL ON C##KH.EMPLOYEE TO C##MYBATIS;
GRANT SELECT ON C##KH.DEPARTMENT TO C##MYBATIS;
GRANT SELECT ON C##KH.JOB TO C##MYBATIS;

-- 동의어 생성
-- SYNONYM : C##KH.EMPLOYEE == emp

-- 동의어를 생성할 수 있는 권한을 MYBATIS 계정에 부여(관리자계정에서) 
GRANT CREATE SYNONYM TO C##MYBATIS; 

-- 동의어를 생성(MYBATIS계정에서)
CREATE SYNONYM EMP FOR C##KH.EMPLOYEE;
CREATE SYNONYM DEPT FOR C##KH.DEPARTMENT;
CREATE SYNONYM JOB FOR C##KH.JOB;